# Generated by Django 4.0.2 on 2022-03-01 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ItemSizer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(blank=True, default='', max_length=100)),
                ('item_link_associate', models.TextField(default='', max_length=500)),
                ('item_pictures', models.TextField(default='', max_length=500)),
                ('item_description', models.TextField(default='', max_length=100)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
