# Generated by Django 4.0.2 on 2022-03-01 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemsizer',
            name='item_link_associate',
        ),
    ]
