# Generated by Django 4.0.2 on 2022-03-01 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_itemsizer_item_link_associate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemsizer',
            name='item_description',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='itemsizer',
            name='item_pictures',
            field=models.CharField(default='', max_length=500),
        ),
    ]
