# Generated by Django 4.0.2 on 2022-03-01 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_itemsizer_item_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemsizer',
            name='url_amazon',
            field=models.CharField(default='', max_length=500),
        ),
    ]
